# Site settings
title: pmanek
author: Petr Mánek
email: citrushunter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I code. I take pictures. I review films. Sometimes, I also like to sleep.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:    petrmanek
github_username:     petrmanek
instagram_username:  petrmanek

# Build settings
markdown: kramdown
